### ISSUE TITLE
Folder vendor is missing

### ISSUE THREAD

**Issue by jgallardo64** [avinashn/paypal-payment-gateway-integration-laravel#2]
![screenshot_1](https://user-images.githubusercontent.com/34686129/52880731-10822a00-3163-11e9-8a3e-2f189ac01a35.png)
The folder vendor is missing in the repository. That way the app can't work.

Could you upload it? Thanks

**Comment by avinashn** [comment]
The 'vendor' folder should not be uploaded.
You will get the 'vendor' folder by running `composer install` on the root
of the project.
