### ISSUE TITLE
Class 'Illuminate\Support\Facades\Input' not found

### ISSUE THREAD

**Issue by JohnCarlos007** [avinashn/paypal-payment-gateway-integration-laravel#7]
![image](https://user-images.githubusercontent.com/64250077/100544552-94060000-3291-11eb-9940-5141aec50704.png)
![image](https://user-images.githubusercontent.com/64250077/100545539-48eeeb80-3297-11eb-924c-17fa7a3bf570.png)

I copied the code for paypal integration and this is the error.

Laravel Framework: 8.1

**Comment by avinashn** [comment]
You can import `use Illuminate\Support\Facades\Input;` at the top or can replace it with `Request::get()` and try.
